ratings:
  namespace: student27-bookinfo-prd
  image: ghcr.io/bordee2000/bookinfo-ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  host: itkmitl.bookinfo.opsta.net
  path: "/student27/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:  
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
  COMMIT_SHA: CHANGEME
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-prd-ratings-mongodb-secret: mongodb-password